name: Build TensorFlow Lite for Windows
run-name: ${{ github.actor }} is building TensorFlow Lite for Windows w/CMake 🚀

on:
  workflow_dispatch:

jobs:
  build-tflite-win:
    runs-on: windows-latest
    steps:
      - name: Check out TFLite-Build repository
        uses: actions/checkout@v4

      - name: Check out TensorFlow repository
        uses: actions/checkout@v4
        with:
          repository: tensorflow/tensorflow
          ref: 2.19.0
          path: tensorflow

      - name: Apply patches
        run: git apply ${{ github.workspace }}\0001-Force-TFLite-Windows-DLL-export.patch
        working-directory: tensorflow

      #
      # To use Bazel
      #
      - run: bazelisk build -c opt //tensorflow/lite/c:tensorflowlite_c
        working-directory: tensorflow

      #
      # To use CMake
      #
      # - run: mkdir build
      # To use ClangCL, AVX flags must be disabled to work around the /vlen=256 issue:
      #   https://github.com/llvm/llvm-project/issues/126888
      # - run: |
      #     cmake -TClangCL \
      #       -DXNNPACK_ENABLE_AVX256SKX=OFF -DXNNPACK_ENABLE_AVX256VNNI=OFF -DXNNPACK_ENABLE_AVX256VNNIGFNI=OFF \
      #       ${{ github.workspace }}\tensorflow\tensorflow\lite\c
      # - run: cmake ${{ github.workspace }}\tensorflow\tensorflow\lite\c
      #   working-directory: build
      # - run: cmake --build . --target RelWithDebInfo -j
      #   working-directory: build

      # - name: Dump exports
      #   run: dumpbin build\Debug\tensorflowlite_c.dll /EXPORTS

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensorflowlite_c
          path: |
            build\Debug\tensorflowlite_c.dll
            build\Debug\tensorflowlite_c.lib
            build\Debug\tensorflowlite_c.pdb
