name: Build TensorFlow Lite for Windows w/CMake
run-name: ${{ github.actor }} is building TensorFlow Lite for Windows w/CMake 🚀

on:
  workflow_dispatch:

jobs:

  Build-TFLite-Windows-CMake:
    runs-on: windows-latest
    steps:

      - name: Show workspace
        run: Get-ChildItem ${{ github.workspace }}

      - name: Check out TensorFlow repository
        uses: actions/checkout@v4
        with:
            repository: tensorflow/tensorflow

      - name: Show workspace
        run: Get-ChildItem ${{ github.workspace }}

      - name: Check out TFLite-Build repository
        uses: actions/checkout@v4
        with:
            repository: wadetb/tflite-build

      - name: Show workspace
        run: Get-ChildItem ${{ github.workspace }}

      - name: Apply patches
        run: git apply ${{ github.workspace }}\tflite-build\0001-Force-TFLite-Windows-DLL-export.patch
        working-directory: tensorflow

      - run: mkdir build

      - run: cmake ${{ github.workspace }}\tensorflow\lite\c
        working-directory: build

      - run: cmake --build . -j
        working-directory: build

      # - name: Dump exports
      #   run: dumpbin build\Debug\tensorflowlite_c.dll /EXPORTS

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensorflowlite_c
          path: |
            build\Debug\tensorflowlite_c.dll
            build\Debug\tensorflowlite_c.lib
            build\Debug\tensorflowlite_c.pdb
