name: Build TensorFlow Lite for Windows w/CMake
run-name: ${{ github.actor }} is building TensorFlow Lite for Windows w/CMake 🚀

on:
  workflow_dispatch:

jobs:

  Build-TFLite-Windows-CMake:
    runs-on: windows-latest
    steps:

      - name: Check out TensorFlow Lite repository
        uses: actions/checkout@v4
        with:
            repository: tensorflow/tensorflow

      - name: Check out TFLite-Build repository
        uses: actions/checkout@v4
        with:
            repository: wadetb/tflite-build

      - name: Apply patches
        run: |
          git apply ../tflite-build/0001-Force-TFLite-Windows-DLL-export.patch
        working-directory: tensorflow

      - run: mkdir tflite-build
      - run: cmake ${{ github.workspace }}\tensorflow\lite\c
        working-directory: tflite-build
      - run: cmake --build . -j
        working-directory: tflite-build

      # - name: Dump exports
      #   run: dumpbin tflite-build\Debug\tensorflowlite_c.dll /EXPORTS

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tensorflowlite_c
          path: |
            tflite-build\Debug\tensorflowlite_c.dll
            tflite-build\Debug\tensorflowlite_c.lib
            tflite-build\Debug\tensorflowlite_c.pdb
